language: node_js

node_js:
  - 7.9.0

cache:
  - yarn: true
  - directories:
    - node_modules

services:
  - mongodb

before_script:
  - sleep 15
  - mongo --eval 'db.getName()'

script:
  - yarn lint
  - mongo --eval 'db.getName()'
  - yarn test
  - mongo --eval 'db.getName()'
  - yarn wds &

